compra:
    path:     /
    defaults: { _controller: "MainBundle:Compra:listarCompras" }
    
nueva_compra:
    path:     /nueva
    defaults: { _controller: "MainBundle:Compra:nuevaCompra" }
    
editar_compra:
    path:     /{id}/editar
    defaults: { _controller: "MainBundle:Compra:editar" }
    
compra_lista:
    path:     /lista
    defaults: { _controller: "MainBundle:Compra:listar" }
    options:
        expose: true
        
guardar_nueva_compra:
    path:     /guardar
    defaults: { _controller: "MainBundle:Compra:guardarNuevaCompra" }
compra_lista_editar:
    path:     /listaeditar
    defaults: { _controller: "MainBundle:Compra:listarEditar" }
    options:
        expose: true
