compra_listar:
    path:     /
    defaults: { _controller: "MainBundle:Compra:listar" }
    
compra_nueva:
    path:     /nueva
    defaults: { _controller: "MainBundle:Compra:nueva" }
    
compra_editar:
    path:     /{id}/editar
    defaults: { _controller: "MainBundle:Compra:editar" }
        
compra_guardar:
    path:     /guardar
    defaults: { _controller: "MainBundle:Compra:guardar" }
    options:
        expose: true
        
compra_listar_detalle:
    path:     /listarDetalle
    defaults: { _controller: "MainBundle:Compra:listarDetalle" }
    options:
        expose: true
