sucursal:
    path:     /
    defaults: { _controller: "MainBundle:Sucursal:index" }

sucursal_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Sucursal:show" }

sucursal_new:
    path:     /new
    defaults: { _controller: "MainBundle:Sucursal:new" }

sucursal_create:
    path:     /create
    defaults: { _controller: "MainBundle:Sucursal:create" }
    methods:  POST

sucursal_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Sucursal:edit" }

sucursal_update:
    path:     /{id}/update
    defaults: { _controller: "MainBundle:Sucursal:update" }
    methods:  [POST, PUT]

sucursal_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Sucursal:delete" }
    methods:  [POST, DELETE]
    
sucursal_seleccion:
    path:     /seleccion
    defaults: { _controller: "MainBundle:Sucursal:seleccionar" }
    
